name = "iw2wth"
default_targets = ["win32", "win64", "appimage", "macos"]
build_directory = "makelove-build"
icon_file = "_DO_NOT_INCLUDE/icon.png"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-./_DO_NOT_INCLUDE/*",
    "-./docs/*",
    "-./rust/*",
]

[windows.exe_metadata]
ProductName = "I Want to Worm the Hole"
CompanyName = "IW2WTH Team"
LegalCopyright = "Copyright © 2026 IW2WTH Team. Mari0 engine portions © 2006-2023 Maurice Guégan"

[linux.desktop_file_metadata]
Name = "I Want to Worm the Hole"

[macos.app_metadata]
CFBundleName = "I Want to Worm the Hole"
CFBundleIdentifier = "com.latentfidelity.iw2wth"
NSHumanReadableCopyright = "Copyright © 2026 IW2WTH Team. Mari0 engine portions © 2006-2023 Maurice Guégan"
