use std::{
    collections::{BTreeMap, BTreeSet},
    env,
    error::Error,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use iw2wth_core::{MappackSettings, Mari0Level};

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = env::args().skip(1);

    match args.next().as_deref() {
        Some("inventory") => run_inventory(args.collect()),
        Some("validate-content") => run_validate_content(args.collect()),
        Some(command) => Err(format!("unknown xtask command: {command}").into()),
        None => Err(
            "usage: cargo run -p xtask -- <inventory|validate-content> [--write docs/file.md]"
                .into(),
        ),
    }
}

fn run_inventory(args: Vec<String>) -> Result<(), Box<dyn Error>> {
    let options = parse_write_options(args, "inventory")?;
    let repo_root = find_repo_root(env::current_dir()?)?;
    let report = build_lua_inventory(&repo_root)?;

    write_or_print(&repo_root, options.write_path, &report)
}

fn run_validate_content(args: Vec<String>) -> Result<(), Box<dyn Error>> {
    let options = parse_write_options(args, "validate-content")?;
    let repo_root = find_repo_root(env::current_dir()?)?;
    let report = validate_content(&repo_root)?;

    write_or_print(&repo_root, options.write_path, &report.markdown)?;

    if report.error_count > 0 {
        Err(format!("content validation found {} errors", report.error_count).into())
    } else {
        Ok(())
    }
}

fn parse_write_options(args: Vec<String>, command: &str) -> Result<CommandOptions, Box<dyn Error>> {
    let mut write_path = None;
    let mut index = 0;

    while index < args.len() {
        match args[index].as_str() {
            "--write" => {
                index += 1;
                let Some(path) = args.get(index) else {
                    return Err("--write requires a path".into());
                };
                write_path = Some(PathBuf::from(path));
            }
            arg => return Err(format!("unknown {command} argument: {arg}").into()),
        }
        index += 1;
    }

    Ok(CommandOptions { write_path })
}

fn write_or_print(
    repo_root: &Path,
    write_path: Option<PathBuf>,
    contents: &str,
) -> Result<(), Box<dyn Error>> {
    if let Some(path) = write_path {
        let path = if path.is_absolute() {
            path
        } else {
            repo_root.join(path)
        };

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, contents)?;
    } else {
        print!("{contents}");
    }

    Ok(())
}

#[derive(Debug)]
struct CommandOptions {
    write_path: Option<PathBuf>,
}

fn find_repo_root(mut dir: PathBuf) -> Result<PathBuf, Box<dyn Error>> {
    loop {
        if dir.join("main.lua").is_file() && dir.join("mappacks").is_dir() {
            return Ok(dir);
        }

        if !dir.pop() {
            return Err("could not find IW2WTH repo root".into());
        }
    }
}

fn build_lua_inventory(repo_root: &Path) -> Result<String, Box<dyn Error>> {
    let mut files = Vec::new();
    collect_lua_files(repo_root, repo_root, &mut files)?;
    files.sort();

    let mut modules = files
        .iter()
        .map(|path| inspect_lua_file(repo_root, path))
        .collect::<Result<Vec<_>, _>>()?;
    modules.sort_by(|left, right| {
        right
            .love_calls
            .cmp(&left.love_calls)
            .then_with(|| right.lines.cmp(&left.lines))
            .then_with(|| left.path.cmp(&right.path))
    });

    let mut output = String::new();
    writeln!(output, "# Lua Module Inventory")?;
    writeln!(output)?;
    writeln!(
        output,
        "Generated by `cargo run -p xtask -- inventory --write docs/lua-inventory.generated.md`."
    )?;
    writeln!(output)?;
    writeln!(
        output,
        "| File | Lines | Functions | Classes | Requires | `love.*` Calls | Conversion Lane |"
    )?;
    writeln!(output, "| --- | ---: | ---: | ---: | ---: | ---: | --- |")?;

    for module in modules {
        writeln!(
            output,
            "| `{}` | {} | {} | {} | {} | {} | {} |",
            module.path,
            module.lines,
            module.functions,
            module.classes,
            module.requires,
            module.love_calls,
            module.lane,
        )?;
    }

    Ok(output)
}

fn validate_content(repo_root: &Path) -> Result<ContentValidationReport, Box<dyn Error>> {
    let entity_catalog = parse_entity_catalog(repo_root)?;
    let mappacks_dir = repo_root.join("mappacks");
    let mut entries = fs::read_dir(&mappacks_dir)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    let mut mappacks = Vec::new();
    let mut errors = Vec::new();
    let mut entity_usage = BTreeMap::new();

    for entry in entries {
        if !entry.file_type()?.is_dir() {
            continue;
        }

        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        let mut report = MappackValidation {
            name,
            settings_name: None,
            settings_author: None,
            level_count: 0,
            total_cells: 0,
            min_width: None,
            max_width: None,
            entity_cells: 0,
            link_targets: 0,
            flags: BTreeSet::new(),
        };

        let settings_path = path.join("settings.txt");
        if settings_path.is_file() {
            let settings = MappackSettings::parse(&fs::read_to_string(&settings_path)?);
            report.settings_name = settings.name;
            report.settings_author = settings.author;
        } else {
            errors.push(format!("{}/settings.txt missing", report.name));
        }

        let mut text_files = fs::read_dir(&path)?.collect::<Result<Vec<_>, _>>()?;
        text_files.sort_by_key(|entry| entry.path());

        for text_file in text_files {
            let text_path = text_file.path();
            if text_path
                .extension()
                .is_none_or(|extension| extension != "txt")
            {
                continue;
            }

            let file_name = text_file.file_name().to_string_lossy().to_string();
            if matches!(file_name.as_str(), "settings.txt" | "version.txt") {
                continue;
            }

            let relative = relative_path(repo_root, &text_path)?;
            match Mari0Level::parse(&fs::read_to_string(&text_path)?) {
                Ok(level) => {
                    report.level_count += 1;
                    report.total_cells += level.cells().len();
                    report.min_width = Some(match report.min_width {
                        Some(width) => width.min(level.width()),
                        None => level.width(),
                    });
                    report.max_width = Some(match report.max_width {
                        Some(width) => width.max(level.width()),
                        None => level.width(),
                    });

                    let properties = &level.properties;
                    if properties.custom_background {
                        report.flags.insert("custom-background");
                    }
                    if properties.underwater {
                        report.flags.insert("underwater");
                    }
                    if properties.has_warp_zone {
                        report.flags.insert("warp-zone");
                    }
                    if properties.intermission {
                        report.flags.insert("intermission");
                    }
                    if properties.bonus_stage {
                        report.flags.insert("bonus-stage");
                    }

                    for (cell_index, cell) in level.cells().iter().enumerate() {
                        report.link_targets += cell.link_targets().len();

                        if cell.values.len() <= 1 {
                            continue;
                        }

                        let x = cell_index % level.width() + 1;
                        let y = cell_index / level.width() + 1;
                        let Some(entity_id) = cell.entity_id() else {
                            errors.push(format!(
                                "{relative}:{x},{y}: non-integral entity id in second cell component"
                            ));
                            continue;
                        };

                        if entity_id == 0 {
                            errors.push(format!("{relative}:{x},{y}: entity id 0 is invalid"));
                            continue;
                        }

                        report.entity_cells += 1;
                        let usage = entity_usage
                            .entry(entity_id)
                            .or_insert_with(|| EntityUsage::new(entity_id, &entity_catalog));
                        usage.count += 1;
                        usage.mappacks.insert(report.name.clone());
                    }
                }
                Err(error) => errors.push(format!("{relative}: {error}")),
            }
        }

        mappacks.push(report);
    }

    build_content_validation_report(mappacks, entity_usage, errors)
}

fn build_content_validation_report(
    mappacks: Vec<MappackValidation>,
    entity_usage: BTreeMap<u16, EntityUsage>,
    errors: Vec<String>,
) -> Result<ContentValidationReport, Box<dyn Error>> {
    let total_mappacks = mappacks.len();
    let total_levels: usize = mappacks.iter().map(|mappack| mappack.level_count).sum();
    let total_cells: usize = mappacks.iter().map(|mappack| mappack.total_cells).sum();
    let total_entity_cells: usize = mappacks.iter().map(|mappack| mappack.entity_cells).sum();
    let total_link_targets: usize = mappacks.iter().map(|mappack| mappack.link_targets).sum();
    let error_count = errors.len();

    let mut output = String::new();
    writeln!(output, "# Content Validation Report")?;
    writeln!(output)?;
    writeln!(
        output,
        "Generated by `cargo run -p xtask -- validate-content --write docs/content-validation.generated.md`."
    )?;
    writeln!(output)?;
    writeln!(output, "- Mappacks scanned: {total_mappacks}")?;
    writeln!(output, "- Levels parsed: {total_levels}")?;
    writeln!(output, "- Total cells parsed: {total_cells}")?;
    writeln!(output, "- Entity cells parsed: {total_entity_cells}")?;
    writeln!(output, "- Link targets parsed: {total_link_targets}")?;
    writeln!(output, "- Entity types used: {}", entity_usage.len())?;
    writeln!(output, "- Errors: {error_count}")?;
    writeln!(output)?;
    writeln!(
        output,
        "| Mappack | Settings Name | Author | Levels | Width Range | Cells | Entity Cells | Links | Flags |"
    )?;
    writeln!(
        output,
        "| --- | --- | --- | ---: | --- | ---: | ---: | ---: | --- |"
    )?;

    for mappack in &mappacks {
        let width_range = match (mappack.min_width, mappack.max_width) {
            (Some(min), Some(max)) if min == max => min.to_string(),
            (Some(min), Some(max)) => format!("{min}-{max}"),
            _ => "n/a".to_owned(),
        };
        let flags = if mappack.flags.is_empty() {
            String::new()
        } else {
            mappack.flags.iter().copied().collect::<Vec<_>>().join(", ")
        };

        writeln!(
            output,
            "| `{}` | {} | {} | {} | {} | {} | {} | {} | {} |",
            mappack.name,
            mappack.settings_name.as_deref().unwrap_or(""),
            mappack.settings_author.as_deref().unwrap_or(""),
            mappack.level_count,
            width_range,
            mappack.total_cells,
            mappack.entity_cells,
            mappack.link_targets,
            flags,
        )?;
    }

    let mut usage = entity_usage.into_values().collect::<Vec<_>>();
    usage.sort_by(|left, right| {
        right
            .count
            .cmp(&left.count)
            .then_with(|| left.id.cmp(&right.id))
    });

    writeln!(output)?;
    writeln!(output, "## Entity Usage")?;
    writeln!(output)?;
    writeln!(output, "| ID | Entity | Count | Mappacks |")?;
    writeln!(output, "| ---: | --- | ---: | --- |")?;

    for entity in usage {
        writeln!(
            output,
            "| {} | `{}` | {} | {} |",
            entity.id,
            entity.name,
            entity.count,
            entity
                .mappacks
                .iter()
                .map(String::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        )?;
    }

    if !errors.is_empty() {
        writeln!(output)?;
        writeln!(output, "## Errors")?;
        writeln!(output)?;
        for error in &errors {
            writeln!(output, "- {error}")?;
        }
    }

    Ok(ContentValidationReport {
        markdown: output,
        error_count,
    })
}

fn parse_entity_catalog(repo_root: &Path) -> Result<Vec<String>, Box<dyn Error>> {
    let bytes = fs::read(repo_root.join("entity.lua"))?;
    let contents = String::from_utf8_lossy(&bytes);
    let mut in_entity_list = false;
    let mut entities = Vec::new();

    for line in contents.lines() {
        let trimmed = line.trim();

        if !in_entity_list {
            if trimmed.starts_with("entitylist") && trimmed.contains('{') {
                in_entity_list = true;
            }
            continue;
        }

        if trimmed.starts_with('}') {
            break;
        }

        let Some(start) = trimmed.find('"') else {
            continue;
        };
        let Some(end) = trimmed[start + 1..].find('"') else {
            continue;
        };

        entities.push(trimmed[start + 1..start + 1 + end].to_owned());
    }

    if entities.is_empty() {
        Err("entity catalog parser found no entities in entity.lua".into())
    } else {
        Ok(entities)
    }
}

fn relative_path(repo_root: &Path, path: &Path) -> Result<String, Box<dyn Error>> {
    Ok(path
        .strip_prefix(repo_root)?
        .to_string_lossy()
        .replace('\\', "/"))
}

#[derive(Debug)]
struct ContentValidationReport {
    markdown: String,
    error_count: usize,
}

#[derive(Debug)]
struct MappackValidation {
    name: String,
    settings_name: Option<String>,
    settings_author: Option<String>,
    level_count: usize,
    total_cells: usize,
    min_width: Option<usize>,
    max_width: Option<usize>,
    entity_cells: usize,
    link_targets: usize,
    flags: BTreeSet<&'static str>,
}

#[derive(Debug)]
struct EntityUsage {
    id: u16,
    name: String,
    count: usize,
    mappacks: BTreeSet<String>,
}

impl EntityUsage {
    fn new(id: u16, catalog: &[String]) -> Self {
        let name = catalog
            .get(usize::from(id - 1))
            .cloned()
            .unwrap_or_else(|| "unknown".to_owned());

        Self {
            id,
            name,
            count: 0,
            mappacks: BTreeSet::new(),
        }
    }
}

fn collect_lua_files(
    repo_root: &Path,
    dir: &Path,
    files: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn Error>> {
    let mut entries = fs::read_dir(dir)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            if should_skip_dir(repo_root, &path) {
                continue;
            }
            collect_lua_files(repo_root, &path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "lua") {
            files.push(path);
        }
    }

    Ok(())
}

fn should_skip_dir(repo_root: &Path, path: &Path) -> bool {
    let Ok(relative) = path.strip_prefix(repo_root) else {
        return true;
    };

    matches!(
        relative.to_string_lossy().as_ref(),
        ".git" | "makelove-build" | "rust/target"
    )
}

fn inspect_lua_file(repo_root: &Path, path: &Path) -> Result<LuaModule, Box<dyn Error>> {
    let bytes = fs::read(path)?;
    let contents = String::from_utf8_lossy(&bytes);
    let relative = path
        .strip_prefix(repo_root)?
        .to_string_lossy()
        .replace('\\', "/");
    let lines = contents.lines().count();
    let love_calls = contents.matches("love.").count();

    let mut functions = 0;
    let mut classes = 0;
    let mut requires = 0;

    for line in contents.lines() {
        let trimmed = line.trim_start();

        if trimmed.starts_with("function ") {
            functions += 1;
        }

        if trimmed.contains("= class:new()") {
            classes += 1;
        }

        if trimmed.starts_with("require ") || trimmed.starts_with("require(") {
            requires += 1;
        }
    }

    Ok(LuaModule {
        lane: conversion_lane(&relative, love_calls),
        path: relative,
        lines,
        functions,
        classes,
        requires,
        love_calls,
    })
}

fn conversion_lane(path: &str, love_calls: usize) -> &'static str {
    if matches!(path, "main.lua" | "menu.lua" | "game.lua" | "editor.lua") {
        "runtime split"
    } else if love_calls == 0 {
        "core candidate"
    } else {
        "adapter-bound"
    }
}

#[derive(Debug)]
struct LuaModule {
    path: String,
    lines: usize,
    functions: usize,
    classes: usize,
    requires: usize,
    love_calls: usize,
    lane: &'static str,
}
